# Generated by Django 5.2.17 on 2026-10-02 08:25

import datetime
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Adjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('minutes', models.IntegerField(help_text='Positive adds to the balance, negative subtracts.')),
                ('paid_out', models.BooleanField(default=False, help_text="The removed hours are paid at the hourly rate with that month's salary.")),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='First day these terms apply.')),
                ('end_date', models.DateField(blank=True, help_text='Last day of employment, if known.', null=True)),
                ('workdays', models.CharField(default='0,1,2,3,4', help_text='Regular working weekdays, 0 = Monday … 6 = Sunday, comma separated.', max_length=13)),
                ('default_start', models.TimeField(default=datetime.time(15, 0))),
                ('default_end', models.TimeField(default=datetime.time(19, 0))),
                ('monthly_salary', models.DecimalField(decimal_places=2, default=Decimal('2166.67'), max_digits=8)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=Decimal('25.00'), max_digits=6)),
                ('night_flat_rate', models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='Paid per overnight stay.', max_digits=6)),
                ('night_from', models.TimeField(default=datetime.time(22, 0), help_text='Overnight hours from here are not paid hourly.')),
                ('night_until', models.TimeField(default=datetime.time(6, 0), help_text='…until this time the next morning.')),
                ('km_rate', models.DecimalField(decimal_places=2, default=Decimal('0.30'), max_digits=4)),
                ('vacation_days_per_year', models.DecimalField(decimal_places=1, default=Decimal('25'), max_digits=4)),
                ('nanny', models.ForeignKey(blank=True, limit_choices_to={'role': 'nanny'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(unique=True)),
                ('kind', models.CharField(choices=[('regular', 'Regular'), ('not_needed', 'Not needed'), ('sick', 'Sick')], default='regular', max_length=12)),
                ('planned_start', models.TimeField(blank=True, null=True)),
                ('planned_end', models.TimeField(blank=True, null=True)),
                ('actual_start', models.TimeField(blank=True, null=True)),
                ('actual_end', models.TimeField(blank=True, null=True)),
                ('break_minutes', models.PositiveSmallIntegerField(blank=True, help_text='Leave empty for the legal default (30 min above 6 hours).', null=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(help_text='The day the engagement starts.')),
                ('kind', models.CharField(choices=[('evening', 'Evening'), ('overnight', 'Overnight')], default='evening', max_length=10)),
                ('start', models.TimeField()),
                ('end', models.TimeField(help_text='An end before the start means the next morning.')),
                ('settlement', models.CharField(choices=[('paid', 'Paid'), ('time_off', 'Time off')], default='time_off', help_text='Overnights are always paid.', max_length=10)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'start'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('route', models.CharField(help_text='e.g. Home → school → swimming → home', max_length=200)),
                ('purpose', models.CharField(max_length=200)),
                ('km', models.DecimalField(decimal_places=1, max_digits=6)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('note', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
