# Generated by Django 5.2.17 on 2026-10-02 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='route',
        ),
    ]
