# Generated by Django 5.2.17 on 2026-10-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_remove_trip_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='kind',
            field=models.CharField(choices=[('regular', 'Regular'), ('not_needed', 'No care needed'), ('sick', 'Sick')], default='regular', max_length=12),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Declined')], default='pending', max_length=10),
        ),
    ]
